CREATE DATABASE IF NOT EXISTS projeto_filmes
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE projeto_filmes;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  perfil ENUM('admin', 'operador') NOT NULL DEFAULT 'operador',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) UNIQUE,
  telefone VARCHAR(30),
  documento VARCHAR(30) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS generos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(80) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS filmes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT,
  ano_lancamento INT,
  genero_id INT,
  preco_locacao DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  estoque INT NOT NULL DEFAULT 0,
  capa_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_filmes_generos FOREIGN KEY (genero_id) REFERENCES generos(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS locacoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT NOT NULL,
  usuario_id INT NOT NULL,
  data_locacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_devolucao_prevista DATE NOT NULL,
  data_devolucao DATE,
  valor_total DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  status ENUM('aberta', 'devolvida', 'atrasada', 'cancelada') NOT NULL DEFAULT 'aberta',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_locacoes_clientes FOREIGN KEY (cliente_id) REFERENCES clientes(id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_locacoes_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS itens_locacao (
  id INT AUTO_INCREMENT PRIMARY KEY,
  locacao_id INT NOT NULL,
  filme_id INT NOT NULL,
  quantidade INT NOT NULL DEFAULT 1,
  valor_unitario DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_itens_locacao_locacoes FOREIGN KEY (locacao_id) REFERENCES locacoes(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_itens_locacao_filmes FOREIGN KEY (filme_id) REFERENCES filmes(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT IGNORE INTO generos (id, nome) VALUES
  (1, 'Acao'),
  (2, 'Comedia'),
  (3, 'Drama'),
  (4, 'Ficcao Cientifica');
